### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by AXDOOMER** [AXDOOMER/mochadoom#4]
List of TODOs (for version 1.7), copied from the old README.md:

- [ ] Fix a bug that allows the player to see through walls.
- [x] Fix a crash between Doom II MAP20 and MAP21.
- [ ] Fix game settings not being saved.
- [x] Adjust the default settings.
- [ ] Display the correct quit messages.
- [x] Fix the different details of rendering.
- [ ] Fix a bug where the player keeps moving forward after the automap has been activated.
- [ ] Fix other input problems with the keyboard and mouse buttons.
- [x] Add back the mouse vertical movement. Allow it to be disabled using '-novert'.
- [ ] Detect FreeDM and FreeDoom has IWADs.
- [ ] Aspect-ratio correction.
- [ ] Make sure the .jar file executes without the need to specify where the 'main' is.
- [ ] Fix the wall-wiggle glitch / long wall error.
- [x] Fix the size of the 'pause' message.
- [ ] Make the sound pitch better
- [x] Fix desync of DEMO1 and DEMO4 of The Ultimate Doom.
- [x] Restore the classic fuzz-effect (depends on the bitdepth).
- [ ] Write the network code and add multiplayer support. (see https://github.com/AXDOOMER/mochadoom/issues/7)
- [ ] Can't use the spy key during multiplayer demos (don't take a screenshot)
- [ ] Can't play demo files without loading it first with -file
- [ ] Add an OpenGL renderer on version 1.8?

**Comment by GoodSign2017** [comment]
For after merge:
- [ ] Translate multiplayer code
- [ ] Better FreeDoom support: add support for FreeDoom DEH patch
- [ ] Optional mouse look
- [ ] Optional, off-by-default Motion Blur posteffect (its easy to implement, just hook alpha in BufferedRenderer32 to player move event)
- [ ] Restore optional ARGB4444 support
- [ ] By default emulate vanilla bugs that we haven't implemented yet
- [ ] Make a test suit to automatically check vanilla behavior preservation
- [ ] Proper copyright headers
- [ ] As a step forward from good old, yet not accelerated software renderer, would be good to limit direct screen access. Currently, screen is accessed directly by three packages: awt, rr and v. Screen access in awt package is read-only, so it will stay safe, and v package was completely refactored into restrictive DoomGraphicSystem API. The only direct screen accessor left is rr package, thus refactoring it into using API (and extending such API further) would be also sort of priority. If it will be done in 1.7, it would help a lot to implement OpenGL renderer in 1.8
- [ ] Implement or discard unfinished functionality about .doomrc and default.cfg in user folders (to use subfolder for latter?)
- [x] Currently, many keys are mapped manually to their characters. Would be great to refactor all the classes who listen key events and replace manual key mappings by using constants of some dictionary (preferably, an enum).

For merge with "2017 resurrection" version:

- [x]  Investigate and fix wrong colormaps on gunfire
- [x] default.cfg option is ignored when choosing renderer bit depth
- [x] player_t.fixedcolormap can be written to vanilla-format files, but currently can be out of vanilla range (256 on invulnerability in TrueColor renderer, 32 on invulnerability in vanilla)
- [x] TYPE_INT_ARGB mode is not supported by new TrueColor renderer, but old one did support that. Add configuration options, proper bppMode.AlphaTrueColor and support for it into BufferedRenderer32
- [x] Add option to reuse Maes written unique blurry effect version
- [x] Fix wrong screen being captured on screenshot
- [x] ~~In Colors.java make RGB conversion methods behave like in dcolors.java of DMUtils~~ Looks wrong if done
- [x] Lightmap generation and tints do not respect COLORMAP lump in loaded WAD files unless in Indexed color mode; should implement more complex, more robust LUT generation with fallback to current behavior
- [x] Bug: ammo part of statusbar does not get empty when switching to chainsaw
- [x] Bug: multiplayer statusbar does not show proper background
- [x] Check default.cfg for changes before writing at game exit to not write unchanged file (or it goes by default in unstaged changes)
- [x] By default emulate even vanilla bugs we are already aware of
- [x] Add support for FreeDM
- [x] Should add a config option to process graphics patch columns in serial way without multithreading (currently only can choose amount of parallel threads)
- [x] Find a way to make sure that default.cfg file always gets populated with settings as close as possible to vanilla
- [x] Fix crash with "NoSuchMethodException" when trying to specify +map command line argument
- [x] Warp command line argument is interpreted wrongly
- [x] Check game exit function for commented/removed code
- [x] RendererFactory does not perform sanity check on WAD-loaded COLORMAP
- [x] Fix bugs with spy camera key and demos
- [ ] Check for other possible bugs and stabilize the version
- [ ] Review all changes made to the project

**Comment by GoodSign2017** [comment]
![no-more-approximation](https://cloud.githubusercontent.com/assets/27532688/25069330/e968ef2c-2286-11e7-84ac-1e5681621c9e.png)

**Comment by AXDOOMER** [comment]
Nice. I have checked it in my checklist.

**Comment by GoodSign2017** [comment]
Upcoming feature (not yet polished):

![doom0009](https://cloud.githubusercontent.com/assets/27532688/25090197/892d6f0c-238a-11e7-9d88-dafb96b26217.png)

On TrueColor with cinvert.wad from these (Experimental Colormap hacks for Doom by Sven "ptoing" Ruthner):


[chacks.zip](https://github.com/AXDOOMER/mochadoom/files/925655/chacks.zip)

**Comment by GoodSign2017** [comment]
More progress on the feature. Colors are somewhat different from indexed, but I cannot say yet, whether this is wrong interpretation of COLORMAP hack, or an effect of proper TrueColor lighting tried hard to be built upon it...

![circus wad](https://cloud.githubusercontent.com/assets/27532688/25110984/c43462a2-23f0-11e7-9627-95fb1709c753.png)
[https://www.doomworld.com/forum/topic/74663-alternate-colormap-falloffs/#comment-1422665](https://www.doomworld.com/forum/topic/74663-alternate-colormap-falloffs/#comment-1422665)
Download wad: [circus.wad.zip](https://github.com/AXDOOMER/mochadoom/files/927073/circus.wad.zip)

Now smoother color transitions:
![doom0011](https://cloud.githubusercontent.com/assets/27532688/25129378/74c8437c-2446-11e7-8c93-152a5a205a7b.png)
- 2017/04/18

**Comment by GoodSign2017** [comment]
Ultimate DOOM: gamma.wad and original
![gammawad](https://cloud.githubusercontent.com/assets/27532688/25112202/6b106c9a-23f8-11e7-97f4-8ce279652208.png)
[gamma.zip](https://github.com/AXDOOMER/mochadoom/files/927150/gamma.zip)
[https://www.doomworld.com/forum/topic/74663-alternate-colormap-falloffs/?page=2#comment-1423841](https://www.doomworld.com/forum/topic/74663-alternate-colormap-falloffs/?page=2#comment-1423841)
